const ERROR_CODES = {
  INTERNAL_ERROR: 'Internal server error',
  AUTH_REQUIRED: 'Authentication required',
  INVALID_CREDENTIALS: 'Invalid username or password',
  INVALID_TOKEN: 'Invalid or expired token',
  USER_NOT_FOUND: 'User not found',
  ACCOUNT_INACTIVE: 'Account is inactive. Contact your administrator.',
  FORBIDDEN: 'Forbidden',
  ADMIN_NOT_FOUND: 'Admin not found',
  INVALID_ROLE: 'Invalid role',
  INVALID_STATUS: 'Invalid status',
  USERNAME_EXISTS: 'Username already exists',
  CANNOT_DEACTIVATE_SELF: 'Cannot deactivate your own account',
  CANNOT_DELETE_SELF: 'Cannot delete your own account',
  INGREDIENT_NOT_FOUND: 'Ingredient not found',
  INGREDIENT_REQUIRED: 'Ingredient is required',
  DISH_NOT_FOUND: 'Dish not found',
  DISH_NOT_FOUND_OR_INACTIVE: 'Dish not found or inactive',
  DISH_NO_RECIPE: 'Dish has no recipe defined',
  PURCHASE_NOT_FOUND: 'Purchase not found',
  PURCHASE_IN_INVENTORY_ONLY: 'Only in-inventory purchases can be handed to chief',
  PURCHASE_ALREADY_RECEIVED: 'Purchase already received',
  PURCHASE_MUST_BE_HANDED: 'Purchase must be handed by purchaser before receiving',
  TRANSFER_NOT_FOUND: 'Transfer not found',
  TRANSFER_NOT_AUTHORIZED: 'Not authorized to accept this transfer',
  TRANSFER_NOT_PENDING: 'Transfer is not pending acceptance',
  INVALID_PURCHASER: 'Invalid purchaser',
  AMOUNT_MUST_BE_POSITIVE: 'Amount must be positive',
  QUANTITY_MUST_BE_POSITIVE: 'Quantity must be positive',
  UNIT_PRICE_MUST_BE_POSITIVE: 'Unit price must be positive',
  STOCK_BELOW_ZERO: 'Stock cannot go below zero',
  INSUFFICIENT_STOCK: 'Insufficient stock',
  INSUFFICIENT_PLATE_STOCK: 'Insufficient plate stock for today',
  PRICE_NOT_SET: 'Price not set for weight type',
  SLICE_COUNT_REQUIRED: 'Slice count is required for slice sales',
  INVALID_WEIGHT_TYPE: 'Invalid weight type',
  SELLER_NOT_FOUND: 'Seller not found or inactive',
  SELLER_INVALID_ROLE: 'Seller must be an employee or chief',
  SCREENSHOT_NOT_FOUND: 'Screenshot not found',
  SCREENSHOT_REQUIRED: 'Screenshot is required',
  SCREENSHOT_TOO_LARGE: 'Screenshot must be 5MB or smaller',
  SCREENSHOT_INVALID_TYPE: 'Only image screenshots are allowed (JPEG, PNG, WebP, GIF)',
  VALIDATION_USERNAME_REQUIRED: 'Username is required',
  VALIDATION_PASSWORD_REQUIRED: 'Password is required',
  VALIDATION_NAME_REQUIRED: 'Name is required',
  VALIDATION_PASSWORD_MIN: 'Password must be at least 6 characters',
  VALIDATION_INVALID_ROLE: 'Invalid role',
  VALIDATION_INVALID_UNIT: 'Invalid unit',
  VALIDATION_AMOUNT_POSITIVE: 'Amount must be positive',
  VALIDATION_PURCHASER_REQUIRED: 'Purchaser is required',
  VALIDATION_INGREDIENT_REQUIRED: 'Ingredient is required',
  VALIDATION_QUANTITY_POSITIVE: 'Quantity must be positive',
  VALIDATION_UNIT_PRICE_POSITIVE: 'Unit price must be positive',
  VALIDATION_DISH_REQUIRED: 'Dish is required',
  VALIDATION_INVALID_WEIGHT_TYPE: 'Invalid weight type',
  VALIDATION_INVALID_PAYMENT: 'Invalid payment method',
  VALIDATION_SLICE_COUNT_REQUIRED: 'Slice count is required for slice sales',
  VALIDATION_INVALID_SELLER: 'Invalid seller',
  VALIDATION_PLATES_POSITIVE: 'Plates count must be positive',
  VALIDATION_PLATE_WEIGHT_REQUIRED: 'Plate weight is required',
  VALIDATION_QUANTITY_DELTA_REQUIRED: 'Quantity delta is required',
  VALIDATION_ITEMS_REQUIRED: 'At least one item is required',
  VALIDATION_FAILED: 'Validation failed',
  EXPENSE_NOT_FOUND: 'Expense not found',
  RECEIPT_NOT_FOUND: 'Receipt not found',
  VALIDATION_INVALID_EXPENSE_CATEGORY: 'Invalid expense category',
  VALIDATION_DESCRIPTION_REQUIRED: 'Description is required for other expenses',
  VALIDATION_SPENT_AT_REQUIRED: 'Spent date is required',
  SALARY_NOT_SET: 'Monthly salary is not set for this employee',
  SALARY_ALREADY_PAID: 'Salary already paid for this period',
  NOT_AN_EMPLOYEE: 'Target user is not an employee',
  INVALID_PAY_PERIOD: 'Invalid pay period. Use YYYY-MM',
  PURCHASE_SIZE_REQUIRED: 'Size is required for this ingredient (small or large)',
  PURCHASE_SIZE_NOT_ALLOWED: 'Size is not applicable for this ingredient',
  VALIDATION_INVALID_SIZE: 'Invalid size. Use small or large',
  RECIPE_SIZE_REQUIRED: 'Recipe size is required for this ingredient (small or large)',
  RECIPE_SIZE_NOT_ALLOWED: 'Recipe size is not applicable for this ingredient',
};

module.exports = ERROR_CODES;
